# Generated by Django 4.1.1 on 2022-10-16 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriaproducto',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='categoriaproducto',
            old_name='update',
            new_name='updated',
        ),
    ]
