# Generated by Django 4.1.1 on 2022-10-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='contenido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
